# Server port ? Render will override this with its own PORT env variable
server.port=${PORT:8080}

# Your personal details ? change these to your actual info!
app.user.full-name=Keshav_Bhalla
app.user.dob=12032006
app.user.email=keshav1869.be23@chitkara.edu.in
app.user.roll-number=2310991869